[package]
name = "rustopt"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustopt"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
rand = "0.8.5"
rand_distr = "0.4.3"
